# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: log encoded TEST_SECRETE_1
        run:
          echo "${{ secrets.TEST_SECRETE_1 }}" | base64 

      - name: create encoded TEST_SECRETE_2
        run:
          echo "${{ secrets.TEST_SECRETE_2 }}" | base64 > TEST_SECRETE_2.txt

      - name: log decoded TEST_SECRETE_2
        run: 
          echo TEST_SECRETE_2.txt | base64 --decode

          
      - name: create TEST_SECRETE_BASE_64
        run:
          echo "${{ secrets.TEST_SECRETE_BASE_64 }}" | base64 --decode > TEST_SECRETE_BASE_64.txt

      - name: log TEST_SECRETE_BASE_64
        run:
          cat TEST_SECRETE_BASE_64.txt
