# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set Secrete to Env1
        run: echo "TEST_SECRETE_1=${{ secrets.TEST_SECRETE_1 }}" >> $GITHUB_ENV  # 실제 시크릿 사용

      - name: print secrete1
        run: echo "TEST_SECRETE_1 = $TEST_SECRETE_1"

      - name: Set Secrete to Env2
        run: echo "TEST_SECRETE_2=${{ secrets.TEST_SECRETE_2 }}" >> $GITHUB_ENV  # 실제 시크릿 사용

      - name: print secrete2
        run: echo "TEST_SECRETE_2 = $TEST_SECRETE_2"

      - name: log TEST_SECRETE_1
        run: |
          echo "${{ secrets.TEST_SECRETE_1 }}"

      - name: log TEST_SECRETE_2
        run: |
          echo "${{ secrets.TEST_SECRETE_2 }}"
